### ISSUE TITLE
Fatal error:  route /post/pet requires a callback

### ISSUE THREAD

**Issue by amitrjain** [mrVanDalo/swagger-api-mock-docker#4]
Getting following error when starting the tool with  http://petstore.swagger.io/v2/swagger.yaml

Fatal error:  route /post/pet requires a callback

**Comment by mrVanDalo** [comment]
Most likely this is a bug for https://www.npmjs.com/package/swagger-mock-api 
But thanks for sharing, I'll investigate.

By the way I'm realizing there is some new versions out there.

**Comment by nissshh** [comment]
I am also facing this issue. Thanks.

**Comment by chikarav2** [comment]
I faced the same thing, too but was able to run the server.
Put this in the responses section.
```
  '200':
    description: successful operation
```
The error was caused maybe there have to be 200 callback in the option.
Write same code when it happens in the diffrent section.
so the yaml would be look like this.
```
paths:
  /pet:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      description: ''
      operationId: addPet
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
```
